### ISSUE TITLE
try/catch behavior different from Clojure JVM

### ISSUE THREAD

**Issue by mbrezu** [richhickey/clojure-clr#32]
In the Clojure JVM REPL:
    user=> (try (throw (Exception. "Got it.")) (catch Exception ex (println ex)))
    #<Exception java.lang.Exception: Got it.>
    nil

In the Clojure CLR REPL:
    user=> (try (throw (Exception. "Got it.")) (catch Exception ex (println ex)))
    .... throws an exception, snipped stack trace because of easy reproduction ...
    user=> (try (do (throw (Exception. "Got it.")) 1) (catch Exception ex (println ex)))
    #<Exception System.Exception: Got it.
       at lambda_method(Closure )>
    nil

[EDIT: changed the first line in the CLR REPL so it's identical to the line in the JVM REPL.]

**Comment by dmiller** [comment]
Fixed the return type on ThrowExpr.
