### ISSUE TITLE
`Compiler/analyze` is missing in ClojureCLR?

### ISSUE THREAD

**Issue by mbrezu** [richhickey/clojure-clr#37]
... or there is an alternative method I should use?

(I tried converting `clojure.contrib.repl-utils/expression-info` (which uses `Compiler/analyze`) for use on the CLR... and failed :-) ).

**Comment by dmiller** [comment]
I didn't try to name things identically when it comes to compiler internals.  The equivalent to Compiler/analyze is Compiler/GenerateLambda(object form, bool addPrint)

**Comment by mbrezu** [comment]
Ok, thanks, I'll give expression-info another try.

**Comment by mbrezu** [comment]
I can't seem to get expression-info to work on ClojureCLR. Maybe someone else can give it a try?

**Comment by dmiller** [comment]
Solution:

```
    (defn expression-info [expr]
      (let [expr-ast (clojure.lang.Compiler/GenerateAST expr false)]
        (when (.HasClrType expr-ast)
          { :class (.ClrType expr-ast) 
            :primitive? (.IsPrimitive (.ClrType expr-ast))})))
```

Then 

```
    (expression-info '(+ (int 5) (float 10))) => {:class System.Single, :primitive? True}
```
