### ISSUE TITLE
`rotations` from `clojure.contrib.seq-utils` doesn't work on ClojureCLR

### ISSUE THREAD

**Issue by mbrezu** [richhickey/clojure-clr#38]
Apparently, this is because of a weird interaction between `concat`, `drop` and `take`.

Steps to reproduce:
    user=> (concat (drop 1 [1 2]) (take 1 [1 2]))
    (1 2 1)

Which is obviously incorrect.

**Comment by mbrezu** [comment]
Digging deeper into this issue, it appears that:

```
user=> (concat (rest [1 2]) (list (first [1 2])))
(1 2 1)
```

while

```
user=> (defn concat2 [l1 l2]
         (if (empty? l1)
           l2
           (cons (first l1) (concat (rest l1) l2))))
#'user/concat2
user=> (concat2 (rest [1 2]) (list (first [1 2])))
(2 1)
```

and considering that

```
user=> (chunked-seq? (rest [1 2]))
True
user=> (chunked-seq? (list (first [1 2])))
False
```

, it appears that the problem lies somehow with chunked sequences.

[EDIT: changed 'chunked sets' to 'chunked sequences' at the end.]

**Comment by mbrezu** [comment]
This small fix
    diff --git a/Clojure/Clojure/Lib/ArrayChunk.cs b/Clojure/Clojure/Lib/ArrayChunk.cs
    index dfdcbb4..c148ec2 100644
    --- a/Clojure/Clojure/Lib/ArrayChunk.cs
    +++ b/Clojure/Clojure/Lib/ArrayChunk.cs
    @@ -28,7 +28,7 @@ namespace clojure.lang
             #region C-tors

```
         public ArrayChunk(object[] array, int off)
-            : this(array,0,array.Length)
+            : this(array,off,array.Length)
         {
         }
```

seems to resolve the issue.

**Comment by dmiller** [comment]
Fixed bug in ArrayChunk ctor.  Closed by cf4b152be5e07d6542d40a94d7a08708719a3cd9

**Comment by dmiller** [comment]
mbrezu: Thanks for tracking this one down. --David

**Comment by mbrezu** [comment]
You're welcome :-)

This bug was looking very threatening/hard to fix, but was surprisingly easy to fix (given enough time -- 4 nights of sleeping over it apparently squashed it without any other "intellectual effort").
