### ISSUE TITLE
A few small installing/building issues and a fix

### ISSUE THREAD

**Issue by kurtschelfthout** [richhickey/clojure-clr#39]
Hi,

Overall, I managed to install and build ClojureCLR without much trouble. Cool.

1) My main suggestion is to give a default layout of the project in the install page, e.g. something like "download the latest dlr to DLR_Main under the folder where you installed ClojureCLR. Build the DLR solution. Now build the Clojure solution". The problem I ran into was that after linking the DLR projects to where I had installed them, I needed to remove and add some references in Visual Studio, and also it seems that some of the DLR output folders were in unexpected places if II didn't put the DLR_Main folder where the ClojureCLR solution expects it.

2) The bootstrap compiler crashed because it could not found junit.clj. The fix is simple: the properties of this file in Clojure.Source are not set to "Copy If Newer".

Hope this helps.

Kurt

**Comment by kurtschelfthout** [comment]
Oh, and an even smaller nag: it is mentioned in the running instructions that Clojure.Main is set as the startup project. This is actually not the case, as startup projects are saved in the .suo file, which is in .gitignore.

**Comment by dmiller** [comment]
Fixed.  Thanks for the input.
