### ISSUE TITLE
clojure.lang.Compiler/LOCAL_ENV not public

### ISSUE THREAD

**Issue by mbrezu** [richhickey/clojure-clr#41]
clojure.lang.Compiler/LOCAL_ENV is public in Clojure, but internal in ClojureCLR. This means that tricks like debug-repl https://gist.github.com/256129/981be4991d4d47fe856476b4c00d046c31823bd6
are not possible using ClojureCLR.

Maybe LOCAL_ENV & Co should be public in ClojureCLR too?

(they could in theory be accesed using explicit reflection and BindingFlags.NonPublic, but that seems to be overkill).

**Comment by dmiller** [comment]
Moved to assembla
