### ISSUE TITLE
RT.load fails when Assembly.GetEntryAssembly() is null.

### ISSUE THREAD

**Issue by btatnall** [richhickey/clojure-clr#46]
When using NUnit and Excel Assembly.GetEntryAssembly() is not present. 

RT.GetFindFilePaths() should do a null check before calling Location and yielding.

**Comment by dmiller** [comment]
Check for null EntryAssembly in RT.GetFindFilePaths.  Closed by d6085a354427522c2f3bc8a84fd9778cf0457d79
