### ISSUE TITLE
There is no special site for Clojure CLR and no documentation

### ISSUE THREAD

**Issue by hoornet** [richhickey/clojure-clr#47]
If a project is to become popular it has to offer at least a:
- Getting started
- My first CLR app
- What is CLR anyway?
  etc

I would help but unfortunately am only a newbie in Clojure, but if you need me in this capacity I am available.

**Comment by dmiller** [comment]
I just pushed a commit updating the readme on the github site.

The github site is the special site for ClojureCLR.  The documentation is on the wiki on the github site.  I updated the links on the readme to reflect recent changes in the wiki.

I also indicated that CLR = Common Language Runtime, the execution engine of the .Net framework.

-David
