### ISSUE TITLE
Ratios convert to int differently in CLR clojure

### ISSUE THREAD

**Issue by ghost** [richhickey/clojure-clr#48]
In CLR Clojure (1.2.0):
user=> (int (/ 4 5))
1

In Java Clojure (1.2.0):
user=> (int (/ 4 5))
0

**Comment by dmiller** [comment]
Works correctly in 1.3.0.

Not sure I want to deal with patches to 1.2 at this point.  Can you upgrade?

-David

**Comment by ghost** [comment]
Sorry, I should have checked the latest to see if this had been fixed. Upgrading is no problem. Thanks.
