### ISSUE TITLE
spit function 'ignores' :append true 

### ISSUE THREAD

**Issue by rippinrobr** [richhickey/clojure-clr#53]
If I run the following code in the JVM based REPL of Clojure 1.3 I end up with a text file that has two lines like the documentation states it should:

(spit "hi.txt" "Test 1\n" :append true)
(spit "hi.txt" "Test 2\n" :append true)
(println (slurp "hi.txt")) 

prints out:

Test 1
Test 2

If I run the same code in the Clojure 1.3 CLR based REPL I end up with a one line hi.txt file that has Test 2.  when I looked at hi.txt in notepad it only had one line also.  It appears that the spit function ignores the append true option.

**Comment by dmiller** [comment]
Hi, Rob.

I'll take a look this weekend.

I noticed your post on getting started with ClojureCLR from a few days ago.
 I'm happy to help if you run into difficulties.  I'm interested in what
you see that would improve the experience.

-David

**Comment by rippinrobr** [comment]
David,
Thank you for looking into it.  So far I would say what others have said is the lack of example code out there.  What I have been using is the interop page on the github wiki.  That has helped me so far.  Since I am pretty new to Clojure most of issues haven't been CLR issues just getting familiar with Clojure itself.  I really appreciate what you are trying to do with the survey and get a community built around ClojureCLR. After I get a little more comfortable with Clojure, I will be more than happy to jump in and help in whatever way I can.  I really want the CLR version to be a viable option for people like me.
I am going to start working on another blog post today about how to instantiate objects and interact with their properties and instance methods.  It will be pretty short but will have enough to help someone get going.  I was working on the code for the blog when I found the spit issue.  I'm going to follow that post up with the porting of my 'Hugo' project to the CLR.  Is there anything you'd like to see me blog about from a new ClojureCLR but seasoned .NET programmer's prospective?
Let me know if there is anything that I can do to help.
Thank you,
Rob Rowe

> Date: Thu, 3 Nov 2011 10:40:13 -0700
> From: reply@reply.github.com
> To: rippinrobr@hotmail.com
> Subject: Re: [clojure-clr] spit function 'ignores' :append true  (#53)
> 
> Hi, Rob.
> 
> I'll take a look this weekend.
> 
> I noticed your post on getting started with ClojureCLR from a few days ago.
>  I'm happy to help if you run into difficulties.  I'm interested in what
> you see that would improve the experience.
> 
> -David
> 
> On Thu, Nov 3, 2011 at 11:56 AM, Rob Rowe <

**Comment by dmiller** [comment]
Lack of documentation is definitely an issue here.

Clojure 1.4.0-master-SNAPSHOT
user=> (spit "hi.txt" "Test 1\n" :file-mode System.IO.FileMode/Append)
nil
user=> (spit "hi.txt" "Test 2\n" :file-mode System.IO.FileMode/Append)
nil
user=> (println (slurp "hi.txt"))
WARNING: (slurp f enc) is deprecated, use (slurp f :encoding enc).
Test 1
Test 2

Generally, the options available are ones that can be handled by the appropriate methods/ctors in System.IO.

In the source:  

   Common options include

```
 :buffer-size   Ths size of buffer to use (default: 1024).
 :file-share    A value from the System.IO.FileShare enumeration.
 :file-mode     A value from the System.IO.FileMode enumeration.
 :file-access   A value from the System.IO.FileAccess enumeration.
 :file-options  A value from the System.IO.FileOptions enumeration.
 :encoding  The encoding to use, either as a string, e.g. \"UTF-8\",
            a keyword, e.g. :utf-8, or a an System.Text.Encoding instance,
            e.g., (System.Text.UTF8Encoding.)
```

More documentation is most certainly needed.

**Comment by rippinrobr** [comment]
David thank you for the clarification.  I will be a little more thorough in my investigation before I report an issue next time.
Sent from my Verizon Wireless BlackBerry

-----Original Message-----
From: David Miller reply@reply.github.com
Date: Tue, 22 Nov 2011 04:39:17 
To: rippinrobr@hotmail.com
Subject: Re: [clojure-clr] spit function 'ignores' :append true  (#53)

Lack of documentation is definitely an issue here.

Clojure 1.4.0-master-SNAPSHOT
user=> (spit "hi.txt" "Test 1\n" :file-mode System.IO.FileMode/Append)
nil
user=> (spit "hi.txt" "Test 2\n" :file-mode System.IO.FileMode/Append)
nil
user=> (println (slurp "hi.txt"))
WARNING: (slurp f enc) is deprecated, use (slurp f :encoding enc).
Test 1
Test 2

Generally, the options available are ones that can be handled by the appropriate methods/ctors in System.IO.

In the source:  

   Common options include
   
     :buffer-size   Ths size of buffer to use (default: 1024).
     :file-share    A value from the System.IO.FileShare enumeration.
     :file-mode     A value from the System.IO.FileMode enumeration.
     :file-access   A value from the System.IO.FileAccess enumeration.
     :file-options  A value from the System.IO.FileOptions enumeration.
     :encoding  The encoding to use, either as a string, e.g. \"UTF-8\",
                a keyword, e.g. :utf-8, or a an System.Text.Encoding instance,
                e.g., (System.Text.UTF8Encoding.)

More documentation is most certainly needed.

---

**Comment by dmiller** [comment]
You shouldn't have to be all that thorough.  Documentation would be nice.
 Someday.

On Tue, Nov 22, 2011 at 6:01 AM, Rob Rowe <
reply@reply.github.com

**Comment by rippinrobr** [comment]
David, you want me to write something up on the spit function?  If you want I can start writing some docs?

**Comment by dmiller** [comment]
Probably all of clr.io could use documentation.  Not sure where to put it,
maybe on the wiki.  You are welcome to start.

On Tue, Nov 22, 2011 at 2:24 PM, Rob Rowe <
reply@reply.github.com
