### ISSUE TITLE
(vector-of :float <ratio>) incorrect

### ISSUE THREAD

**Issue by rickbeerendonk** [richhickey/clojure-clr#54]
Version: Clojure Clr 1.3.0 Debug 4.0 (download)

Input REPL:
(vector-of :float 1/2 1/3)

Output (Clr) - incorrect:
[5.0 3.333333E+15]

Output (Java) - correct:
[0.5 0.33333334]

**Comment by dmiller** [comment]
What's 15 orders of magnitude between friends?

ClojureCLR no longer hosted on this site.  Go to github.com/clojure/clojure-clr for updates.

Also, you can create issues at  http://dev.clojure.org/jira/browse/CLJCLR

I'll work on this tonight.

-David

**Comment by rickbeerendonk** [comment]
LOL
Quick reply! I was just learning, so it is not a big issue for me now.

Also watch the 1/2 become 5.0

I found the new sites, but I had limited time to register and look around at the Jira site. I will create new issues there.

**Comment by dmiller** [comment]
Under Debug 4.0 and under Debug 3.5

Clojure 1.4.0-master-SNAPSHOT
user=> (float 1/2)
0.5
user=> (float 1/3)
0.3333333
user=> (vector-of :float 1/2 1/3)
[0.5 0.3333333]
user=>

What version of Clojure are you running?
What version of .Net?
Release or Debug version?  (If you just brought down the binary package,
that's Release).
Operating system version?  32bit or 64bit?

I don't know what other variables to ask about.

-David

On Mon, Jan 2, 2012 at 12:15 PM, Rick Beerendonk <
reply@reply.github.com

**Comment by rickbeerendonk** [comment]
Windows 7 64-bit, .NET 4.0
Clojure Clr 1.3.0 Debug 4.0 (download) & Clojure 1.4.0-master-SNAPSHOT

---

The problem is with the decimal separator. I am in The Netherlands and we use a comma instead of a point. I saw incorrect behaviour in the following method in clojure.lang.BigDecimal:

```
    public double ToDouble(IFormatProvider provider)
    {
        // As j.m.BigDecimal puts it: "Somewhat inefficient, but guaranteed to work."
        return Double.Parse(ToString(), provider);
    }
```

[Ratio = 1/2]
this.ToString() = "0.5" [Type = string]
Double.Parse(this.ToString(), null) = 5.0 [Type = double]

[Ratio = 1/3]
this.ToString() = "0.3333333333333333" [Type = string]
Double.Parse(this.ToString(), null) = 3333333333333333.0 [Type = double]

ToString() usually uses the same culture as Parse(), but here it is calling BigDecimal's "public string ToScientificString()" method. In the ToScientificString() method the decimal separator is hardcoded as a point in multiple places.

**Comment by dmiller** [comment]
Ah.  I must admit to be culturally insensitive sometimes.   My code is
American. :)

I must admit to going back and forth a little on this.  If you read the
docs on Clojure, no mention is made of the Lisp reader being
culture-sensitive.   In fact, specifically, the comma is defined as
whitespace.  Most programming languages are not.  They may be so in output,
but not in source code.

My code obviously is not consistent on this point.  I'll need to make
parsers and output culture-insensitive.  Sigh.

On Tue, Jan 3, 2012 at 10:20 AM, Rick Beerendonk <
reply@reply.github.com

**Comment by rickbeerendonk** [comment]
Having a point as a decimal separator in code is normal for every coder. Delphi and C# are not different than Clojure. Only when a decimal is transformed into a string or parsed from a string, things get interesting. It is best to be explicit about the culture, not implicit.

I will dive into the code and user groups a little more this weekend.

**Comment by dmiller** [comment]
I just pushed a commit that I hope fixes your problem.

-David

On Tue, Jan 3, 2012 at 11:35 AM, Rick Beerendonk <
reply@reply.github.com

**Comment by rickbeerendonk** [comment]
Excellent!
Tests confirm the issue is fixed. Thank you!
